version: '3.1'
services:
  stations:
    container_name: stations
    image: stations:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/stations
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mysql-db
    networks:
      - evgo-network
  mysql-db:
    container_name: stations-mysql
    image: mysql:latest
    restart: always

    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=stations
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - evgo-network

networks:
  evgo-network:
    driver: bridge
