version: '3.1'
services:
  mysql:
    container_name: stations-mysql
    image: mysql:latest
    restart: always

    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=stations
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: