version: '3.1'
services:
  stations:
    container_name: stations
    image: stations:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - MYSQL_HOST=stations-db
      - MYSQL_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stations-db:3306/stations
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - stations-db
    networks:
      - evgo-network
  stations-db:
    container_name: stations-db
    image: postgis/postgis:11-3.3-alpine
    restart: always

    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=stations
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - evgo-network

networks:
  evgo-network:
    driver: bridge
