spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stations
    driver-class-name: org.postgresql.Driver
    username: stations-service
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
