version: '3.1'
services:
  mysql:
    container_name: stations-mysql
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=stations
      - MYSQL_USER=stations-service
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=s3cr3t
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: